# Generated by Django 6.1.1 on 2026-09-29 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fermeture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi'), ('dimanche', 'Dimanche')], max_length=10)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('fermeture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux_bloques', to='core.fermeture')),
                ('horaire_ouverture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='core.horaireouverture')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGalerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_image', models.ImageField(upload_to='galerie/')),
                ('titre', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('prestation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_galerie', to='core.prestation')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('reservation_pour_soi', models.BooleanField(default=True)),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=100)),
                ('prenom_beneficiaire', models.CharField(blank=True, max_length=100)),
                ('telephone_beneficiaire', models.CharField(blank=True, max_length=20)),
                ('commentaire_client', models.TextField(blank=True, max_length=500)),
                ('creneau', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='core.creneau')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.prestation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('reference_stripe', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paiement', to='core.reservation')),
            ],
        ),
    ]
